/**
 * Mock application catalog — 20+ real open-source projects.
 *
 * In production this will be fetched from Supabase. The mock
 * data lets us build and test the entire UI without a backend.
 */

import type { Application, Category, InstalledApp } from './types';

// ─── Categories ──────────────────────────────────────────────────────────────
export const categories: Category[] = [
  { id: 'ai-tools', name: 'AI Tools', slug: 'ai-tools', icon: 'Brain', color: '#a78bfa', description: 'Artificial intelligence and machine learning tools' },
  { id: 'productivity', name: 'Productivity', slug: 'productivity', icon: 'Briefcase', color: '#60a5fa', description: 'Boost your workflow and organization' },
  { id: 'development', name: 'Development', slug: 'development', icon: 'Code', color: '#34d399', description: 'Developer tools, editors, and IDEs' },
  { id: 'media', name: 'Media', slug: 'media', icon: 'Film', color: '#f472b6', description: 'Audio, video, and streaming software' },
  { id: 'design', name: 'Design', slug: 'design', icon: 'Palette', color: '#fb923c', description: 'Graphics, illustration, and 3D design' },
  { id: 'privacy', name: 'Privacy & Security', slug: 'privacy', icon: 'Shield', color: '#2dd4bf', description: 'Protect your data and privacy' },
  { id: 'self-hosting', name: 'Self-hosting', slug: 'self-hosting', icon: 'Server', color: '#818cf8', description: 'Host services on your own hardware' },
  { id: 'utilities', name: 'Utilities', slug: 'utilities', icon: 'Wrench', color: '#94a3b8', description: 'System tools and everyday utilities' },
  { id: 'games', name: 'Games & Engines', slug: 'games', icon: 'Gamepad2', color: '#e879f9', description: 'Game engines, emulators, and open-source games' },
  { id: 'education', name: 'Education', slug: 'education', icon: 'GraduationCap', color: '#facc15', description: 'Learning platforms and educational tools' },
];

// ─── Applications ────────────────────────────────────────────────────────────
export const applications: Application[] = [
  {
    id: '1',
    name: 'OBS Studio',
    slug: 'obs-studio',
    description: 'Free and open-source software for video recording and live streaming.',
    long_description: 'OBS Studio is a powerful, free, and open-source software for video recording and live streaming. It supports real-time video/audio capturing, scene composition, encoding, recording, and broadcasting. Works with Twitch, YouTube, Facebook Live, and many more platforms.',
    icon_url: 'https://obsproject.com/assets/images/new_icon_small-r.png',
    category_id: 'media',
    license: 'GPL-2.0',
    repository_url: 'https://github.com/obsproject/obs-studio',
    official_website: 'https://obsproject.com',
    documentation_url: 'https://obsproject.com/wiki/',
    developer: 'OBS Project',
    organization: 'obsproject',
    platforms: ['windows', 'macos', 'linux'],
    architectures: ['x64'],
    latest_version: '31.0.1',
    installation_methods: ['OFFICIAL_INSTALLER'],
    difficulty: 'easy',
    is_featured: true,
    download_count: 285000,
    star_count: 62000,
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2025-06-20T00:00:00Z',
  },
  {
    id: '2',
    name: 'Blender',
    slug: 'blender',
    description: 'Professional free and open-source 3D creation suite.',
    long_description: 'Blender is a free and open-source 3D creation suite. It supports the entirety of the 3D pipeline — modeling, rigging, animation, simulation, rendering, compositing, and motion tracking. It also includes video editing and 2D animation.',
    icon_url: 'https://download.blender.org/branding/community/blender_community_badge_white.png',
    category_id: 'design',
    license: 'GPL-3.0',
    repository_url: 'https://projects.blender.org/blender/blender',
    official_website: 'https://www.blender.org',
    documentation_url: 'https://docs.blender.org',
    developer: 'Blender Foundation',
    organization: 'blender',
    platforms: ['windows', 'macos', 'linux'],
    architectures: ['x64', 'arm64'],
    latest_version: '4.4.1',
    installation_methods: ['OFFICIAL_INSTALLER'],
    difficulty: 'easy',
    is_featured: true,
    download_count: 420000,
    star_count: 14000,
    created_at: '2024-01-10T00:00:00Z',
    updated_at: '2025-07-01T00:00:00Z',
  },
  {
    id: '3',
    name: 'VLC Media Player',
    slug: 'vlc',
    description: 'Free and open-source cross-platform multimedia player and framework.',
    long_description: 'VLC is a free, open-source, cross-platform multimedia player and framework that plays most multimedia files as well as DVDs, Audio CDs, VCDs, and various streaming protocols. It requires no separate codec installation.',
    icon_url: 'https://images.videolan.org/vlc/images/vlcicon-256.png',
    category_id: 'media',
    license: 'GPL-2.0',
    repository_url: 'https://code.videolan.org/videolan/vlc',
    official_website: 'https://www.videolan.org/vlc/',
    documentation_url: 'https://wiki.videolan.org',
    developer: 'VideoLAN',
    organization: 'videolan',
    platforms: ['windows', 'macos', 'linux'],
    architectures: ['x64', 'arm64'],
    latest_version: '3.0.21',
    installation_methods: ['OFFICIAL_INSTALLER'],
    difficulty: 'easy',
    is_featured: true,
    download_count: 890000,
    star_count: 14500,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2025-05-15T00:00:00Z',
  },
  {
    id: '4',
    name: 'GIMP',
    slug: 'gimp',
    description: 'GNU Image Manipulation Program — a free Photoshop alternative.',
    long_description: 'GIMP is a cross-platform image editor available for GNU/Linux, macOS, Windows, and more. It provides sophisticated tools for photo retouching, image authoring, and graphic design. A powerful alternative to Adobe Photoshop.',
    icon_url: 'https://www.gimp.org/images/frontpage/wilber-big.png',
    category_id: 'design',
    license: 'GPL-3.0',
    repository_url: 'https://gitlab.gnome.org/GNOME/gimp',
    official_website: 'https://www.gimp.org',
    documentation_url: 'https://docs.gimp.org',
    developer: 'GIMP Team',
    organization: 'GNOME',
    platforms: ['windows', 'macos', 'linux'],
    architectures: ['x64'],
    latest_version: '2.10.38',
    installation_methods: ['OFFICIAL_INSTALLER'],
    difficulty: 'easy',
    is_featured: true,
    download_count: 350000,
    star_count: 0,
    created_at: '2024-01-12T00:00:00Z',
    updated_at: '2025-04-10T00:00:00Z',
  },
  {
    id: '5',
    name: 'Open WebUI',
    slug: 'open-webui',
    description: 'User-friendly interface for running AI models locally with Ollama.',
    long_description: 'Open WebUI is an extensible, feature-rich, and user-friendly self-hosted AI interface. It supports various LLM runners including Ollama and OpenAI-compatible APIs. Chat with AI models locally with a beautiful interface reminiscent of ChatGPT.',
    icon_url: 'https://raw.githubusercontent.com/open-webui/open-webui/main/static/favicon.png',
    category_id: 'ai-tools',
    license: 'MIT',
    repository_url: 'https://github.com/open-webui/open-webui',
    official_website: 'https://openwebui.com',
    documentation_url: 'https://docs.openwebui.com',
    developer: 'Open WebUI',
    organization: 'open-webui',
    platforms: ['windows', 'macos', 'linux'],
    architectures: ['x64', 'arm64'],
    latest_version: '0.7.2',
    installation_methods: ['CONTAINER'],
    difficulty: 'moderate',
    is_featured: true,
    download_count: 180000,
    star_count: 75000,
    created_at: '2024-03-01T00:00:00Z',
    updated_at: '2025-07-28T00:00:00Z',
  },
  {
    id: '6',
    name: 'Ollama',
    slug: 'ollama',
    description: 'Get up and running with large language models locally.',
    long_description: 'Ollama lets you run large language models like Llama 3, Mistral, Gemma, and many more on your local machine. Simple CLI interface with an API for integrating into your applications. No cloud required — your data stays on your machine.',
    icon_url: 'https://ollama.com/public/ollama.png',
    category_id: 'ai-tools',
    license: 'MIT',
    repository_url: 'https://github.com/ollama/ollama',
    official_website: 'https://ollama.com',
    documentation_url: 'https://github.com/ollama/ollama/blob/main/README.md',
    developer: 'Ollama',
    organization: 'ollama',
    platforms: ['windows', 'macos', 'linux'],
    architectures: ['x64', 'arm64'],
    latest_version: '0.7.1',
    installation_methods: ['OFFICIAL_INSTALLER'],
    difficulty: 'easy',
    is_featured: true,
    download_count: 320000,
    star_count: 120000,
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2025-07-25T00:00:00Z',
  },
  {
    id: '7',
    name: 'VS Code',
    slug: 'vscode',
    description: 'Lightweight but powerful source code editor by Microsoft.',
    long_description: 'Visual Studio Code is a free, lightweight, and powerful source code editor. It comes with built-in support for JavaScript, TypeScript, and Node.js and has a rich ecosystem of extensions for other languages and runtimes including C++, Java, Python, PHP, and Go.',
    icon_url: 'https://code.visualstudio.com/assets/images/code-stable.png',
    category_id: 'development',
    license: 'MIT',
    repository_url: 'https://github.com/microsoft/vscode',
    official_website: 'https://code.visualstudio.com',
    documentation_url: 'https://code.visualstudio.com/docs',
    developer: 'Microsoft',
    organization: 'microsoft',
    platforms: ['windows', 'macos', 'linux'],
    architectures: ['x64', 'arm64'],
    latest_version: '1.100.0',
    installation_methods: ['OFFICIAL_INSTALLER'],
    difficulty: 'easy',
    is_featured: false,
    download_count: 950000,
    star_count: 168000,
    created_at: '2024-01-05T00:00:00Z',
    updated_at: '2025-07-30T00:00:00Z',
  },
  {
    id: '8',
    name: 'Audacity',
    slug: 'audacity',
    description: 'Free, open-source, cross-platform audio editor and recorder.',
    long_description: 'Audacity is an easy-to-use, multi-track audio editor and recorder for Windows, macOS, Linux, and other operating systems. Record live audio, digitize recordings from other media, cut, copy, splice, or mix sounds together. Change the speed or pitch of a recording.',
    icon_url: 'https://www.audacityteam.org/wp-content/uploads/2024/06/Audacity-Logo.svg',
    category_id: 'media',
    license: 'GPL-3.0',
    repository_url: 'https://github.com/audacity/audacity',
    official_website: 'https://www.audacityteam.org',
    documentation_url: 'https://manual.audacityteam.org',
    developer: 'Audacity Team',
    organization: 'audacity',
    platforms: ['windows', 'macos', 'linux'],
    architectures: ['x64'],
    latest_version: '3.7.3',
    installation_methods: ['OFFICIAL_INSTALLER'],
    difficulty: 'easy',
    is_featured: false,
    download_count: 275000,
    star_count: 13000,
    created_at: '2024-01-20T00:00:00Z',
    updated_at: '2025-06-01T00:00:00Z',
  },
  {
    id: '9',
    name: 'Firefox',
    slug: 'firefox',
    description: 'Fast, private, and free web browser from Mozilla.',
    long_description: 'Firefox is a free and open-source web browser developed by the Mozilla Foundation. It offers strong privacy protections, including Enhanced Tracking Protection, and is built on the Gecko rendering engine. Customizable with thousands of extensions.',
    icon_url: 'https://www.mozilla.org/media/protocol/img/logos/firefox/browser/logo.svg',
    category_id: 'productivity',
    license: 'MPL-2.0',
    repository_url: 'https://hg.mozilla.org/mozilla-central/',
    official_website: 'https://www.mozilla.org/firefox',
    documentation_url: 'https://support.mozilla.org',
    developer: 'Mozilla Foundation',
    organization: 'mozilla',
    platforms: ['windows', 'macos', 'linux'],
    architectures: ['x64', 'arm64'],
    latest_version: '138.0',
    installation_methods: ['OFFICIAL_INSTALLER'],
    difficulty: 'easy',
    is_featured: false,
    download_count: 670000,
    star_count: 0,
    created_at: '2024-01-02T00:00:00Z',
    updated_at: '2025-07-15T00:00:00Z',
  },
  {
    id: '10',
    name: 'Godot Engine',
    slug: 'godot',
    description: 'Feature-packed, cross-platform 2D and 3D game engine.',
    long_description: 'Godot provides a huge set of common tools, so that users can focus on making games without having to reinvent the wheel. Games can be exported to multiple platforms including desktop, mobile, and web. It uses its own scripting language GDScript, but also supports C# and C++.',
    icon_url: 'https://godotengine.org/assets/press/icon_color.png',
    category_id: 'games',
    license: 'MIT',
    repository_url: 'https://github.com/godotengine/godot',
    official_website: 'https://godotengine.org',
    documentation_url: 'https://docs.godotengine.org',
    developer: 'Godot Engine',
    organization: 'godotengine',
    platforms: ['windows', 'macos', 'linux'],
    architectures: ['x64', 'arm64'],
    latest_version: '4.4.1',
    installation_methods: ['PREBUILT_RELEASE'],
    difficulty: 'easy',
    is_featured: true,
    download_count: 190000,
    star_count: 96000,
    created_at: '2024-02-15T00:00:00Z',
    updated_at: '2025-07-10T00:00:00Z',
  },
  {
    id: '11',
    name: 'LibreOffice',
    slug: 'libreoffice',
    description: 'Free office suite — word processing, spreadsheets, presentations, and more.',
    long_description: 'LibreOffice is a powerful and free office suite, used by millions of people around the world. It includes Writer (word processing), Calc (spreadsheets), Impress (presentations), Draw (vector graphics), Base (databases), and Math (formula editing). Compatible with Microsoft Office formats.',
    icon_url: 'https://www.libreoffice.org/themes/libreofficenew/img/logo.svg',
    category_id: 'productivity',
    license: 'MPL-2.0',
    repository_url: 'https://git.libreoffice.org/core',
    official_website: 'https://www.libreoffice.org',
    documentation_url: 'https://documentation.libreoffice.org',
    developer: 'The Document Foundation',
    organization: 'libreoffice',
    platforms: ['windows', 'macos', 'linux'],
    architectures: ['x64', 'arm64'],
    latest_version: '25.2.4',
    installation_methods: ['OFFICIAL_INSTALLER'],
    difficulty: 'easy',
    is_featured: false,
    download_count: 520000,
    star_count: 0,
    created_at: '2024-01-08T00:00:00Z',
    updated_at: '2025-06-28T00:00:00Z',
  },
  {
    id: '12',
    name: 'Krita',
    slug: 'krita',
    description: 'Professional free and open-source digital painting application.',
    long_description: 'Krita is a professional free and open-source painting program. It is made by artists that want to see affordable art tools for everyone. Concept art, texture and matte painters, illustrations, and comics — Krita is designed for all of these.',
    icon_url: 'https://krita.org/wp-content/uploads/2024/01/krita-logo-512.png',
    category_id: 'design',
    license: 'GPL-3.0',
    repository_url: 'https://invent.kde.org/graphics/krita',
    official_website: 'https://krita.org',
    documentation_url: 'https://docs.krita.org',
    developer: 'KDE',
    organization: 'kde',
    platforms: ['windows', 'macos', 'linux'],
    architectures: ['x64'],
    latest_version: '5.2.9',
    installation_methods: ['OFFICIAL_INSTALLER'],
    difficulty: 'easy',
    is_featured: false,
    download_count: 210000,
    star_count: 7500,
    created_at: '2024-01-25T00:00:00Z',
    updated_at: '2025-05-20T00:00:00Z',
  },
  {
    id: '13',
    name: 'Jellyfin',
    slug: 'jellyfin',
    description: 'The free software media system — your own Netflix.',
    long_description: 'Jellyfin is a free software media system that puts you in control of managing and streaming your media. It is an alternative to proprietary services like Plex and Emby. Stream your entire media library from your own server to any device.',
    icon_url: 'https://jellyfin.org/images/logo.svg',
    category_id: 'self-hosting',
    license: 'GPL-2.0',
    repository_url: 'https://github.com/jellyfin/jellyfin',
    official_website: 'https://jellyfin.org',
    documentation_url: 'https://jellyfin.org/docs/',
    developer: 'Jellyfin',
    organization: 'jellyfin',
    platforms: ['windows', 'macos', 'linux'],
    architectures: ['x64', 'arm64'],
    latest_version: '10.10.6',
    installation_methods: ['CONTAINER', 'OFFICIAL_INSTALLER'],
    difficulty: 'moderate',
    is_featured: false,
    download_count: 145000,
    star_count: 40000,
    created_at: '2024-02-20T00:00:00Z',
    updated_at: '2025-07-05T00:00:00Z',
  },
  {
    id: '14',
    name: 'Nextcloud',
    slug: 'nextcloud',
    description: 'Self-hosted cloud storage, contacts, calendar, and collaboration platform.',
    long_description: 'Nextcloud is a suite of client-server software for creating and using file hosting services. It is functionally similar to Dropbox and Google Drive. Replace proprietary cloud services with a self-hosted solution you fully control.',
    icon_url: 'https://nextcloud.com/wp-content/uploads/2024/07/nextcloud-logo.svg',
    category_id: 'self-hosting',
    license: 'AGPL-3.0',
    repository_url: 'https://github.com/nextcloud/server',
    official_website: 'https://nextcloud.com',
    documentation_url: 'https://docs.nextcloud.com',
    developer: 'Nextcloud GmbH',
    organization: 'nextcloud',
    platforms: ['windows', 'macos', 'linux'],
    architectures: ['x64', 'arm64'],
    latest_version: '30.0.6',
    installation_methods: ['CONTAINER'],
    difficulty: 'moderate',
    is_featured: false,
    download_count: 170000,
    star_count: 29000,
    created_at: '2024-02-10T00:00:00Z',
    updated_at: '2025-07-22T00:00:00Z',
  },
  {
    id: '15',
    name: 'KeePassXC',
    slug: 'keepassxc',
    description: 'Cross-platform community-driven password manager.',
    long_description: 'KeePassXC is a free, open-source, and cross-platform password manager. It helps you store and manage your passwords securely. It uses strong encryption to protect your data and supports auto-type, browser integration, SSH agent, and TOTP.',
    icon_url: 'https://keepassxc.org/images/keepassxc-logo.svg',
    category_id: 'privacy',
    license: 'GPL-3.0',
    repository_url: 'https://github.com/keepassxreboot/keepassxc',
    official_website: 'https://keepassxc.org',
    documentation_url: 'https://keepassxc.org/docs/',
    developer: 'KeePassXC Team',
    organization: 'keepassxreboot',
    platforms: ['windows', 'macos', 'linux'],
    architectures: ['x64'],
    latest_version: '2.7.9',
    installation_methods: ['OFFICIAL_INSTALLER'],
    difficulty: 'easy',
    is_featured: false,
    download_count: 230000,
    star_count: 23000,
    created_at: '2024-01-18T00:00:00Z',
    updated_at: '2025-06-15T00:00:00Z',
  },
  {
    id: '16',
    name: 'HandBrake',
    slug: 'handbrake',
    description: 'Open-source video transcoder — convert video from nearly any format.',
    long_description: 'HandBrake is a tool for converting video from nearly any format to a selection of modern, widely supported codecs. It supports batch encoding, chapter markers, subtitles, and various filters. Perfect for converting videos for any device.',
    icon_url: 'https://handbrake.fr/img/logo.png',
    category_id: 'media',
    license: 'GPL-2.0',
    repository_url: 'https://github.com/HandBrake/HandBrake',
    official_website: 'https://handbrake.fr',
    documentation_url: 'https://handbrake.fr/docs/',
    developer: 'HandBrake Team',
    organization: 'HandBrake',
    platforms: ['windows', 'macos', 'linux'],
    architectures: ['x64', 'arm64'],
    latest_version: '1.9.1',
    installation_methods: ['OFFICIAL_INSTALLER'],
    difficulty: 'easy',
    is_featured: false,
    download_count: 160000,
    star_count: 18000,
    created_at: '2024-01-22T00:00:00Z',
    updated_at: '2025-05-25T00:00:00Z',
  },
  {
    id: '17',
    name: 'Inkscape',
    slug: 'inkscape',
    description: 'Professional vector graphics editor — free Illustrator alternative.',
    long_description: 'Inkscape is a free and open-source vector graphics editor. It can be used to create or edit vector graphics such as illustrations, diagrams, line arts, charts, logos, and complex paintings. A powerful alternative to Adobe Illustrator.',
    icon_url: 'https://media.inkscape.org/static/images/inkscape-logo.svg',
    category_id: 'design',
    license: 'GPL-2.0',
    repository_url: 'https://gitlab.com/inkscape/inkscape',
    official_website: 'https://inkscape.org',
    documentation_url: 'https://inkscape.org/learn/',
    developer: 'Inkscape Project',
    organization: 'inkscape',
    platforms: ['windows', 'macos', 'linux'],
    architectures: ['x64'],
    latest_version: '1.4.2',
    installation_methods: ['OFFICIAL_INSTALLER'],
    difficulty: 'easy',
    is_featured: false,
    download_count: 195000,
    star_count: 2500,
    created_at: '2024-01-28T00:00:00Z',
    updated_at: '2025-04-20T00:00:00Z',
  },
  {
    id: '18',
    name: 'Signal Desktop',
    slug: 'signal-desktop',
    description: 'Private messenger — end-to-end encrypted messaging for everyone.',
    long_description: 'Signal is a cross-platform centralized encrypted instant messaging service. Users can send one-to-one and group messages, including files, voice notes, images, and videos. It uses the internet to send end-to-end encrypted messages.',
    icon_url: 'https://signal.org/assets/images/header/logo.png',
    category_id: 'privacy',
    license: 'AGPL-3.0',
    repository_url: 'https://github.com/signalapp/Signal-Desktop',
    official_website: 'https://signal.org',
    documentation_url: 'https://support.signal.org',
    developer: 'Signal Foundation',
    organization: 'signalapp',
    platforms: ['windows', 'macos', 'linux'],
    architectures: ['x64', 'arm64'],
    latest_version: '7.36.0',
    installation_methods: ['OFFICIAL_INSTALLER'],
    difficulty: 'easy',
    is_featured: false,
    download_count: 340000,
    star_count: 15000,
    created_at: '2024-01-06T00:00:00Z',
    updated_at: '2025-07-28T00:00:00Z',
  },
  {
    id: '19',
    name: 'Notepad++',
    slug: 'notepad-plus-plus',
    description: 'Free source code editor and Notepad replacement for Windows.',
    long_description: 'Notepad++ is a free source code editor and Notepad replacement that supports several languages. Running in the MS Windows environment, its use is governed by GPL License. It provides syntax highlighting, code folding, auto-completion, and plugin support.',
    icon_url: 'https://notepad-plus-plus.org/images/logo.svg',
    category_id: 'development',
    license: 'GPL-3.0',
    repository_url: 'https://github.com/notepad-plus-plus/notepad-plus-plus',
    official_website: 'https://notepad-plus-plus.org',
    documentation_url: 'https://npp-user-manual.org',
    developer: 'Don Ho',
    organization: 'notepad-plus-plus',
    platforms: ['windows'],
    architectures: ['x64', 'arm64'],
    latest_version: '8.7.7',
    installation_methods: ['OFFICIAL_INSTALLER'],
    difficulty: 'easy',
    is_featured: false,
    download_count: 480000,
    star_count: 23000,
    created_at: '2024-01-04T00:00:00Z',
    updated_at: '2025-07-18T00:00:00Z',
  },
  {
    id: '20',
    name: '7-Zip',
    slug: '7-zip',
    description: 'Free file archiver with high compression ratio.',
    long_description: '7-Zip is a file archiver with a high compression ratio. It supports 7z, XZ, BZIP2, GZIP, TAR, ZIP, WIM, AR, ARJ, CAB, CHM, CPIO, CramFS, DMG, EXT, FAT, GPT, HFS, IHEX, ISO, LZH, LZMA, MBR, MSI, NSIS, NTFS, QCOW2, RAR, RPM, SquashFS, UDF, UEFI, VDI, VHD, VMDK, WIM, XAR, and Z formats.',
    icon_url: 'https://www.7-zip.org/7ziplogo.png',
    category_id: 'utilities',
    license: 'LGPL-2.1',
    repository_url: 'https://sourceforge.net/projects/sevenzip/',
    official_website: 'https://www.7-zip.org',
    documentation_url: 'https://www.7-zip.org/faq.html',
    developer: 'Igor Pavlov',
    organization: '7-zip',
    platforms: ['windows', 'linux'],
    architectures: ['x64', 'arm64'],
    latest_version: '24.09',
    installation_methods: ['OFFICIAL_INSTALLER'],
    difficulty: 'easy',
    is_featured: false,
    download_count: 720000,
    star_count: 0,
    created_at: '2024-01-03T00:00:00Z',
    updated_at: '2025-03-10T00:00:00Z',
  },
  {
    id: '21',
    name: 'Home Assistant',
    slug: 'home-assistant',
    description: 'Open-source home automation platform — control your smart home.',
    long_description: 'Home Assistant is an open-source home automation platform. It tracks the state of all the devices in your home and lets you create automations. It supports 2000+ integrations with popular IoT devices and services. Run it locally — no cloud required.',
    icon_url: 'https://www.home-assistant.io/images/home-assistant-logo.svg',
    category_id: 'self-hosting',
    license: 'Apache-2.0',
    repository_url: 'https://github.com/home-assistant/core',
    official_website: 'https://www.home-assistant.io',
    documentation_url: 'https://www.home-assistant.io/docs/',
    developer: 'Home Assistant',
    organization: 'home-assistant',
    platforms: ['windows', 'macos', 'linux'],
    architectures: ['x64', 'arm64'],
    latest_version: '2025.7.3',
    installation_methods: ['CONTAINER'],
    difficulty: 'moderate',
    is_featured: false,
    download_count: 195000,
    star_count: 78000,
    created_at: '2024-02-25T00:00:00Z',
    updated_at: '2025-07-30T00:00:00Z',
  },
  {
    id: '22',
    name: 'FileZilla',
    slug: 'filezilla',
    description: 'Free FTP, FTPS, and SFTP client with an intuitive interface.',
    long_description: 'FileZilla Client is a fast and reliable cross-platform FTP, FTPS and SFTP client with lots of useful features and an intuitive graphical user interface. It supports drag and drop, directory comparison, remote file editing, and much more.',
    icon_url: 'https://filezilla-project.org/images/filezilla-logo.svg',
    category_id: 'utilities',
    license: 'GPL-2.0',
    repository_url: 'https://svn.filezilla-project.org/filezilla/',
    official_website: 'https://filezilla-project.org',
    documentation_url: 'https://wiki.filezilla-project.org',
    developer: 'FileZilla Project',
    organization: 'filezilla-project',
    platforms: ['windows', 'macos', 'linux'],
    architectures: ['x64'],
    latest_version: '3.68.1',
    installation_methods: ['OFFICIAL_INSTALLER'],
    difficulty: 'easy',
    is_featured: false,
    download_count: 310000,
    star_count: 0,
    created_at: '2024-01-14T00:00:00Z',
    updated_at: '2025-06-05T00:00:00Z',
  },
  {
    id: '23',
    name: 'LocalAI',
    slug: 'localai',
    description: 'Run AI models locally — drop-in OpenAI API replacement.',
    long_description: 'LocalAI is a free, open-source alternative to OpenAI. It acts as a drop-in replacement REST API compatible with OpenAI API specifications for local inferencing. Run LLMs, generate images, audio, and more locally or on-prem with consumer-grade hardware.',
    icon_url: 'https://localai.io/logo.png',
    category_id: 'ai-tools',
    license: 'MIT',
    repository_url: 'https://github.com/mudler/LocalAI',
    official_website: 'https://localai.io',
    documentation_url: 'https://localai.io/docs/',
    developer: 'Ettore Di Giacinto',
    organization: 'mudler',
    platforms: ['windows', 'macos', 'linux'],
    architectures: ['x64', 'arm64'],
    latest_version: '2.25.0',
    installation_methods: ['CONTAINER', 'PREBUILT_RELEASE'],
    difficulty: 'advanced',
    is_featured: false,
    download_count: 85000,
    star_count: 30000,
    created_at: '2024-03-15T00:00:00Z',
    updated_at: '2025-07-20T00:00:00Z',
  },
  {
    id: '24',
    name: 'Brave Browser',
    slug: 'brave',
    description: 'Fast, privacy-focused browser that blocks ads and trackers by default.',
    long_description: 'Brave is a free and open-source web browser developed by Brave Software, Inc. based on the Chromium web browser. Brave blocks ads and website trackers by default, and provides a way for users to send cryptocurrency contributions to websites and content creators.',
    icon_url: 'https://brave.com/static-assets/images/brave-logo-sans-text.svg',
    category_id: 'privacy',
    license: 'MPL-2.0',
    repository_url: 'https://github.com/nicol/nicol-browser',
    official_website: 'https://brave.com',
    documentation_url: 'https://support.brave.com',
    developer: 'Brave Software',
    organization: 'brave',
    platforms: ['windows', 'macos', 'linux'],
    architectures: ['x64', 'arm64'],
    latest_version: '1.78.102',
    installation_methods: ['OFFICIAL_INSTALLER'],
    difficulty: 'easy',
    is_featured: false,
    download_count: 410000,
    star_count: 18000,
    created_at: '2024-01-09T00:00:00Z',
    updated_at: '2025-07-29T00:00:00Z',
  },
];

// ─── Mock installed apps ─────────────────────────────────────────────────────
export const mockInstalledApps: InstalledApp[] = [
  {
    id: 'inst-1',
    application_id: '3',
    application: applications.find(a => a.id === '3')!,
    version: '3.0.21',
    install_method: 'OFFICIAL_INSTALLER',
    install_path: 'C:\\Program Files\\VideoLAN\\VLC',
    installed_at: '2025-06-10T14:30:00Z',
    updated_at: '2025-06-10T14:30:00Z',
    status: 'stopped',
  },
  {
    id: 'inst-2',
    application_id: '7',
    application: applications.find(a => a.id === '7')!,
    version: '1.99.0',
    install_method: 'OFFICIAL_INSTALLER',
    install_path: 'C:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code',
    installed_at: '2025-05-20T09:15:00Z',
    updated_at: '2025-07-01T10:00:00Z',
    status: 'running',
  },
  {
    id: 'inst-3',
    application_id: '19',
    application: applications.find(a => a.id === '19')!,
    version: '8.7.6',
    install_method: 'OFFICIAL_INSTALLER',
    install_path: 'C:\\Program Files\\Notepad++',
    installed_at: '2025-04-15T16:45:00Z',
    updated_at: '2025-04-15T16:45:00Z',
    status: 'stopped',
  },
];

// ─── Helper: get apps by category ────────────────────────────────────────────
export function getAppsByCategory(categoryId: string): Application[] {
  return applications.filter(a => a.category_id === categoryId);
}

export function getFeaturedApps(): Application[] {
  return applications.filter(a => a.is_featured);
}

export function getPopularApps(limit = 8): Application[] {
  return [...applications].sort((a, b) => b.download_count - a.download_count).slice(0, limit);
}

export function getNewApps(limit = 8): Application[] {
  return [...applications].sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()).slice(0, limit);
}

export function searchApps(query: string): Application[] {
  const q = query.toLowerCase();
  return applications.filter(
    a =>
      a.name.toLowerCase().includes(q) ||
      a.description.toLowerCase().includes(q) ||
      a.long_description.toLowerCase().includes(q) ||
      a.category_id.toLowerCase().includes(q) ||
      a.developer.toLowerCase().includes(q)
  );
}

export function getAppBySlug(slug: string): Application | undefined {
  return applications.find(a => a.slug === slug);
}
